name: PHP CI

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  pull_request:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'  # Specify the PHP version you want to use
        extensions: mbstring, sqlite3  # Add any required PHP extensions

    - name: Install Composer dependencies
      run: |
        cd php_program/embedded  # Change to the directory where composer.json is located
        composer install

    - name: Run tests
      run: |
        cd php_program/embedded  # Change to the directory where tests are located
        # Here you can run your tests, for example:
        # phpunit tests/  # Uncomment this line if you have PHPUnit tests
        echo "No tests defined yet."  # Placeholder for demonstration